khubkhaoRec/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('khubkhaoapp.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/login.html'), name='logout'),
    path('oauth/', include('social_django.urls', namespace='social')),
]

khubkhaoapp/urls.py
from django.urls import path
from khubkhaoapp.views import IndexView, IndexResultView, HomeView


app_name = 'khubkhaoapp'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('khubkhao/', IndexView, name='index'),
    path('result/', IndexResultView, name='result'),
]

khubkhaoapp/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class EthnicFood(models.Model):
    """
    EthnicFood class represents ethnic of food.

    Attributes:
        models.Model(Model): source of information. It contains the essential fields and behaviors of the data.
    """
    ethnic_food_name = models.CharField(
        max_length=20,
        verbose_name='Ethnic food',
        unique=True,
        blank=False,
        help_text='Enter an ethnic food'
    )


    def __str__(self):
        """
        Override to print a readable string presentation of ethnic food.

        Returns:
            str: ethnic of food.
        """
        return self.ethnic_food_name

    class Meta:
        verbose_name = "Ethnic food"
        verbose_name_plural = "Ethnic foods"


class Category(models.Model):
    """
    Category class represents food's category.

    Attributes:
        models.Model(Model): source of information. It contains the essential fields and behaviors of the data.
    """
    type_name = models.CharField(
        max_length=20,
        verbose_name='Category name',
        unique=True,
        blank=False,
        help_text='Enter Category name'
    )


    def __str__(self):
        """
        Override to print a readable string presentation of food's category.

        Returns:
            str: category's name.
        """
        return self.type_name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class Food(models.Model):
    """
    Food class represents informations and details of food.

    Food class represents name, image url, average price, rate, category, and ethnic of food.
    This class also compute rate of food from user rate and rate in database by itself.

    Attributes:
        models.Model (Model): source of information. It contains the essential fields and behaviors of the data.
    """
    food_name = models.CharField(
        max_length=40,
        verbose_name='Food name',
        unique=True,
        blank=False,
        help_text='Enter food name'
    )

    image_location = models.CharField(
        max_length=100,
        verbose_name='Image url',
        unique=True,
        null=True,
        blank=True,
        help_text='Enter url location'
    )

    average_price = models.DecimalField(
        default=0,
        max_digits=5,
        decimal_places=2,
        verbose_name='Average price',
        blank=True,
        null=True,
    )

    original_rate = models.DecimalField(
        default=0,
        max_digits=5,
        decimal_places=2,
        verbose_name='Original Rate',
        blank=True,
        null=True,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(0)
        ],
        help_text='Must be 0-100',
    )

    total_rate = models.DecimalField(
        default=0,
        max_digits=5,
        decimal_places=2,
        verbose_name='Total Rate',
        blank=True,
        null=True,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(0)
        ],
        help_text='Must be 0-100',
    )

    user_rate = models.DecimalField(
        default=0,
        max_digits=9,
        decimal_places=2,
        verbose_name='User Rate',
        blank=True,
        null=True,
        validators=[MinValueValidator(0)],
    )

    user_count = models.PositiveIntegerField(
        default=0,
        blank=True,
        null=True,
        verbose_name='User Count',
        help_text='Must be zero',
    )

    ethnic_food_name = models.ForeignKey(
        EthnicFood,
        on_delete=models.CASCADE,
        verbose_name='Ethnic Food',
        blank=False,
    )

    category = models.ManyToManyField(
        Category,
        verbose_name='Category',
        blank=False
    )

    pk_voted = models.TextField(
        verbose_name='Primary key of user',
        blank=True,
    )

    check_vote = models.BooleanField(
        default=True
    )


    def __str__(self):
        """
        Override to print a readable string presentation of food name.

        Returns:
            str: food name.
        """
        return self.food_name

    def get_average_price(self):
        """
        Get average price of food.

        Returns:
            Decimal: average price of food.
        """
        return self.average_price

    def get_image_location(self):
        """
        Get image url of food.

        Returns:
            str: image url of food.
        """
        return self.image_location

    def add_user_count(self):
        """
        Count the number of user who voted on each food and update into the database.
        """
        self.user_count = float(self.user_count)+1

    def add_user_pk(self, primary_key):
        """
        Add user's primary key that voted on each food into the database.

        Args:
            primary_key (str): user's primary key.
        """
        self.pk_voted = self.pk_voted + str(primary_key) + ","

    def get_user_pk(self):
        """
        Get all primary keys of users which have been voted on each food.

        Returns:
            str: all primary keys of users which have been voted on each food.
        """
        return self.pk_voted

    def set_user_rate(self, value):
        """
        Add rate from user into database.

        Args:
            value (int): rate from user which can be [20, 40, 60, 80, 100].
        """
        self.user_rate = float(self.user_rate)+value

    def set_total_rate(self):
        """
        Set total rate of food which computes from rate in the database and rate from user by 80:20 percent respectively.

        Returns:
            Decimal: total rate of food(0-100) which computes from rate in the database and rate from user.
        """
        float_original = float(self.original_rate)*0.8
        self.total_rate = float_original
        float_user = float(self.user_rate)*0.2
        count = float(self.user_count)
        if(count != 0):
            float_user = float_user/count
        compute_rate = float("{0:.2f}".format(float_user+float_original))
        self.total_rate = compute_rate
        return self.total_rate

    def get_total_rate(self):
        """
        Get food's rate which computes from rate in the database and rate from user.

        Returns:
            Decimal: food's rate(0-100) from rate in the database and rate from user.
        """
        return self.total_rate

    def get_original_rate(self):
        """
        Get food's rate from the database.

        Returns:
            Decimal: food's rate(0-100) from the database.
        """
        return self.original_rate

    def get_user_rate(self):
        """
        Get food's rate from users.

        Returns:
            Decimal: food's rate from users.
        """
        return self.user_rate

    def get_user_count(self):
        """
        Get number of users that voted on the food.

        Returns:
            int: number of users that voted on the food.
        """
        return self.user_count

    def get_ethnic_food_name(self):
        """
        Get all ethnic foods.

        Returns:
            EthnicFood: all ethnic foods.
        """
        return self.ethnic_food_name

    def get_category(self):
        """
        Get all categories of food.

        Returns:
            ManyRelatedManager: categories of food.
        """
        return self.category

    def set_check_false(self):
        """
        Set voteable's status for each food to be False (cannot vote).
        """
        self.check_vote = False

    def set_check_true(self):
        """
        Set voteable's status for each food to be True (can vote).
        """
        self.check_vote = True

    def get_check_vote(self):
        """
        Get voteable's status for each food.

        Returns:
            bool: True if voteable and False if otherwise.
        """
        return self.check_vote

    class Meta:
        verbose_name = "Food"
        verbose_name_plural = "Foods"

khubkhaoapp/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from django.db.models import Q
from enum import Enum
import logging
from khubkhaoapp.models import Category, EthnicFood, Food


logger = logging.getLogger(__name__)


class Rate(Enum):
    """
    An enumeration for rates.
    """
    ONE = 20
    TWO = 40
    THREE = 60
    FOUR = 80
    FIVE = 100


def get_client_ip(request):
    """
    Get an IP of the user.
    """
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        return x_forwarded_for.split(',')[0]
    return request.META.get('REMOTE_ADDR')


def vote_value(raw_number):
    """
    Get rate values from enumeration which can be [20, 40, 60, 80, 100].

    Args:
        raw_number (str): text which used to specify rate values.
    Returns:
        int: rate value which can be [20, 40, 60, 80, 100].
    """
    if(raw_number == "ONE") :
        return Rate.ONE.value
    elif(raw_number == "TWO") :
        return Rate.TWO.value
    elif(raw_number == "THREE") :
        return Rate.THREE.value
    elif(raw_number == "FOUR") :
        return Rate.FOUR.value
    else :
        return Rate.FIVE.value


def filter_ethnic(ethnic):
    """
    Filter ethnic foods which have been chosen from the user.

    Returns:
        EthinicFood: ethnic foods which have been chosen from the user.
    """
    return EthnicFood.objects.filter(id__in=ethnic)


def filter_category(category):
    """
    Filter categories which have been chosen from the user.

    Returns:
        Category: categories which have been chosen from the user.
    """
    return Category.objects.filter(id__in=category)


def filter_food(selected_ethnic,selected_category):
    """
    Filter food's criteria specified by the user.

    Args:
        selected_ethnic (EthinicFood): ethnic foods which have been chosen from user.
        selected_category (Category): categories which have been chosen from user.
    Returns:
        Food: food's criteria specified by the user.
    """
    if not selected_category.exists() and not selected_ethnic.exists():
        return Food.objects.all()
    elif not selected_category.exists() or not selected_ethnic.exists():
        return Food.objects.filter(Q(ethnic_food_name__in=selected_ethnic) | Q(category__in=selected_category)).distinct()
    return Food.objects.filter(ethnic_food_name__in=selected_ethnic).filter(category__in=selected_category).distinct()


def logging_user(request,selected_ethnic,selected_category):
    """
    Logging activities of users when they selected ethnic foods and categories.
    
    Args:
        selected_ethnic (EthinicFood): ethnic foods which have been chosen from user.
        selected_category (Category): categories which have been chosen from user.
    """
    user_ip = get_client_ip(request)
    category = str(selected_category)
    ethnic = str(selected_ethnic)

    if check_authenticated(request):
        user_id = request.user.id
        username = request.user.get_full_name()

        if not selected_category.exists() and not selected_ethnic.exists():
            logger.info('ip: %s id: %d user: %s didn\'t selected.' % (user_ip,user_id,username))
        elif selected_category.exists() and not selected_ethnic.exists():
            logger.info('ip: %s id: %d user: %s is selected %s.' % (user_ip,user_id,username,category))
        elif not selected_category.exists() and selected_ethnic.exists():
            logger.info('ip: %s id: %d user: %s is selected %s.' % (user_ip,user_id,username,ethnic))
        else:
            logger.info('ip: %s id: %d user: %s is selected %s and %s .' % (user_ip,user_id,username,ethnic,category))
    else:
        if not selected_category.exists() and not selected_ethnic.exists():
            logger.info('ip: %s Guest didn\'t selected.' % (user_ip))
        elif selected_category.exists() and not selected_ethnic.exists():
            logger.info('ip: %s Guest is selected %s.' % (user_ip,category))
        elif not selected_category.exists() and selected_ethnic.exists():
            logger.info('ip: %s Guest is selected %s.' % (user_ip,ethnic))
        else:
            logger.info('ip: %s Guest is selected %s and %s.' % (user_ip,ethnic,category))


def sort_food(unsorted_food):
    """
    Sort food by overall rate from users and rate in the database.
    
    Args:
        unsorted_food (list): a list of unsorted food.
    Returns:
        list: a list of sorted foods.
    """
    return sorted(unsorted_food, key = lambda food: food.set_total_rate(), reverse=True)[:25]


def check_vote(request,food_set):
    """
    Check that user is voted food or not.
    Set voteable's status for each food to be False if user is voted,
    True if otherwise. 

    Args:
        food_set (list): a list of foods.
    """
    for food in food_set:
        array = food.get_user_pk().split(',')
        if(str(request.user.pk) in array):
            food.set_check_false()
        else:
            food.set_check_true()
        food.save()


def vote_food(request,pk_food,vote):
    """
    Get vote score and primary key of food that user have been voted and update into the database.

    Args:
        pk_food (str): a primary key which use to specify food that has been voted.
        vote (str): text that use to specify rate value.
    """
    vote_scores = vote_value(vote)
    food = Food.objects.get(pk=pk_food)
    food.add_user_count()
    food.set_user_rate(vote_scores)
    food.add_user_pk(request.user.pk)
    food.save()


def check_authenticated(request):
    """
    Check that the account is authenticated or not.

    Returns:
        bool: True if the account is authenticated, False if otherwise.
    """
    return request.user.is_authenticated and not request.user.is_anonymous


class HomeView(TemplateView):
    """
    Homeview class render a template for a login page.
    """
    template_name = 'registration/login.html'


def IndexView(request):
    """
    IndexView class render an index page with the passed contexts.
    This class also represents all foods in the database.

    Returns:
        HttpResponse: an HttpResponse object with that rendered text.
    """
    user_ip = get_client_ip(request)
    template_name = 'khubkhaoapp/index.html'

    if check_authenticated(request):
        user_id = request.user.id
        username = request.user.get_full_name()
        logger.info('ip: %s id: %d user: %s have been using webpage.' % (user_ip,user_id,username))
        if request.method == "POST":
            my_vote = request.POST.get('rate_star')
            pk_and_vote = my_vote.split(',')
            vote_food(request,pk_and_vote[0],pk_and_vote[1])
            food = Food.objects.get(pk=pk_and_vote[0])
            rate = vote_value(pk_and_vote[1])
            logger.info('ip: %s id: %d user: %s have been vote %s for %s points.' % (user_ip,user_id,username,food,rate))
    else:
        logger.info('ip: %s Guest have been using webpage.' % user_ip)
    
    unsorted_results = Food.objects.all()
    check_vote(request,unsorted_results)
    if request.method == "POST":
        food_list = sort_food(unsorted_results)
    else :
        food_list = sorted(unsorted_results, key = lambda food: food.set_total_rate(), reverse=True)
    category_list = Category.objects.all()
    ethnic_list = EthnicFood.objects.all()
    context = {
        'food_list': food_list,
        'category_list': category_list,
        'ethnic_list': ethnic_list,
    }
    return render(request, template_name, context)
    

def IndexResultView(request):
    """
    IndexResultView class render an index page with the passed contexts and represents 25 foods
    in the database which filtered food's criteria specified by the user.

    Returns:
        HttpResponse: an HttpResponse object with that rendered text.
    """
    template_name = 'khubkhaoapp/index.html'

    if request.method == "POST":
        my_ethnic = request.POST.getlist('ethnic_name')
        my_category = request.POST.getlist('category_name')
        selected_ethnic = filter_ethnic(my_ethnic)
        selected_category = filter_category(my_category)
        logging_user(request,selected_ethnic,selected_category)
        food_list = filter_food(selected_ethnic,selected_category)
    else:
        food_list = Food.objects.all()
    
    check_vote(request,food_list)
    food_list = sort_food(food_list)
    category_list = Category.objects.all()
    ethnic_list = EthnicFood.objects.all()    
    context = {
        'food_list': food_list,
        'category_list': category_list,
        'ethnic_list': ethnic_list,
    }
    return render(request,template_name, context)

khubkhaoapp/templates/khubkhaoapp/index.html
{% extends 'base.html' %}

{% block user %}
{% if user.is_authenticated and not user.is_anonymous %}
<div style="text-align:center;">
    <p><b>Hi, {{ user.get_full_name|default:user.username }}!</b></p>
    <a href="{% url 'logout' %}">
        <button class="btn btn-outline-dark" type="submit">Logout</button>
    </a>
</div>
{% else %}
<div style="text-align:center;">
    <a href="{% url 'khubkhaoapp:home' %}" style="color:#4c352d; text-decoration-line: underline;">
        <h4>Sign in</h4>
    </a>
</div>
{% endif %}

{% endblock %}

{% block body %}
<div class="row" style="padding-left: 30px;">
    <div class="col-md-3">
        <div class="sidebar">
            <div class="row" style="height: 20px;"></div>
            <div class="barcontent">
                <form action="{% url 'khubkhaoapp:result' %}" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <label style="font-size: 20px;">Let's start your meal with select some food ethnic!</label>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group form-check">
                                {% for ethnic in ethnic_list %}
                                <input type="checkbox" class="form-check-input" value={{ethnic.pk}} name="ethnic_name"
                                    id="ethnic{{ forloop.counter }}">
                                <label class="form-check-label" for="ethnic{{ forloop.counter }}">{{ ethnic }}</label>
                                <br>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <label style="font-size: 17px;">Need more specific...?</label>
                        <label style="font-size: 17px;">Choose some choice(s) below.</label>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group form-check">
                                {% for category in category_list %}
                                <input type="checkbox" class="form-check-input" value={{category.pk}} name="category_name"
                                    id="category{{ forloop.counter }}">
                                <label class="form-check-label" for="category{{ forloop.counter }}">{{ category }}</label>
                                <br>
                                {% endfor %}
                            </div>
                            <input class="btn btn-warning btn-lg btn-block" type="submit" value="Submit" />
                            <br>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="content" style="text-align: center;">
            <div class="row"></div>
            <br>
            <h1>~ Generated Result! ~</h1>
            <br>
            <form action="{% url 'khubkhaoapp:index' %}" method="POST">
                {% csrf_token %}
                {% for food in food_list %}
                <div class="row" style="padding: 20px;">
                    <div class="col-4" style="text-align: right;">
                        {% if user.is_authenticated and not user.is_anonymous %}
                        <img src="{{ food.get_image_location }}" width="300px" height="200px" class="border border-warning rounded">
                        {% else %}
                        <img src="{{ food.get_image_location }}" width="233px" height="175px" class="border border-warning rounded">
                        {% endif %}
                    </div>
                    <div class="col-8" style="text-align: left;">
                        <h3><b id="Food_name">{{ food }}</b></h3>
                        <ul>
                            <li>
                                <h5><b id="Price">Average Price:</b> ${{ food.get_average_price }}</h5>
                            </li>
                            <li>
                                <h5><b id="Type">Type:</b> {{ food.get_ethnic_food_name }} </h5>
                            </li>
                            <li>
                                <h5><b id="Categories">Categories:</b> {% for cate in food.get_category.all %} <span class="badge badge-dark">#{{ cate }}</span> {% endfor %}</h5>
                            </li>
                            <li>
                                <h5><b id="Rate">Rate point:</b> {{ food.get_total_rate }} / 100</h5>
                            </li>
                            {% if user.is_authenticated and not user.is_anonymous %}
                                {% if food.get_check_vote %}
                                <li>
                                    <h5><b>Vote:</b>
                                        <span class="badge badge-pill badge-dark">Min</span>--
                                        <button class="btn btn-warning" name="rate_star" value={{food.pk}},ONE id="vote1" type="submit">1</button>
                                        <button class="btn btn-warning" name="rate_star" value={{food.pk}},TWO id="vote2" type="submit">2</button>
                                        <button class="btn btn-warning" name="rate_star" value={{food.pk}},THREE id="vote3" type="submit">3</button>
                                        <button class="btn btn-warning" name="rate_star" value={{food.pk}},FOUR id="vote4" type="submit">4</button>
                                        <button class="btn btn-warning" name="rate_star" value={{food.pk}},FIVE id="vote5" type="submit">5</button>
                                        --<span class="badge badge-pill badge-dark">Max</span>
                                    </h5>
                                </li>
                                {% endif %}
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <br>
                {% endfor %}
            </form>
        </div>
    </div>
</div>
{% endblock %}